# Generated by Django 4.2.13 on 2024-05-16 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleapp', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='CustomUser',
        ),
    ]
