# Generated by Django 4.2.13 on 2024-05-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleapp', '0004_alter_customuser_name_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('phone_number', models.BigIntegerField()),
            ],
        ),
    ]
