# Generated by Django 4.2.13 on 2024-05-16 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teleapp', '0006_globalnumbers_is_spam'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalnumbers',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
